# Generated by Django 5.2 on 2025-04-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_rename_autores_autor_libro_alter_reseñas_libro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reseñas',
            new_name='Reseña',
        ),
    ]
